# Reference https://github.com/docker-library/mongo/issues/246
version: '3.8'
services:
  house_site:
    image: veldrovive/house
    ports:
      - 3006:3006
    command: ./wait-for-mongo.sh
  # mongodb_container:
  #   image: mongo:4.2
  #   network_mode: host
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: rootpassword
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb_data_container:/data/db
  #   command: --replSet replicaset
  mongo:
    image: mongo:4.2
    container_name: mongo
    network_mode: host
    ports:
      - 27017:27017
    restart: always
    volumes:
    - mongo-bin:/usr/bin
    # command: --replSet replicaset
    command: ls /bin

volumes:
  # mongodb_data_container:
    mongo-bin: